# Generated by Django 4.1.1 on 2022-11-23 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomb', models.CharField(max_length=30)),
                ('descrip', models.CharField(max_length=200)),
                ('talla', models.CharField(max_length=3)),
                ('valor', models.IntegerField()),
                ('cant', models.IntegerField()),
                ('tipo', models.CharField(max_length=30)),
                ('imagen', models.ImageField(null=True, upload_to='productos')),
            ],
        ),
        migrations.CreateModel(
            name='compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_comp', models.IntegerField()),
                ('nom_cli', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=60)),
                ('descrip', models.CharField(max_length=200, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cantidad', models.SmallIntegerField()),
                ('valorcomp', models.IntegerField()),
                ('id_prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conex.item')),
            ],
        ),
    ]
